services:

  App.jobOpenings.JobOpeningRepository:
    class: ../../../../../Contexts/LLBE/JobOpenings/infrastructure/persistence/MongoJobOpeningRepository
    arguments: [ '@App.shared.ConnectionManager' ]

  App.jobOpenings.JobOpeningCreator:
    class: ../../../../../Contexts/LLBE/JobOpenings/application/Create/JobOpeningCreator
    arguments: [ '@App.jobOpenings.JobOpeningRepository' ]

  App.jobOpenings.JobOpeningFinder:
    class: ../../../../../Contexts/LLBE/JobOpenings/application/Find/JobOpeningFinder
    arguments: [ '@App.jobOpenings.JobOpeningRepository' ]

  App.jobOpenings.JobOpeningUpgrader:
    class: ../../../../../Contexts/LLBE/JobOpenings/application/Update/JobOpeningUpgrader
    arguments: [ '@App.jobOpenings.JobOpeningRepository' ]

  App.jobOpenings.JobOpeningRemover:
    class: ../../../../../Contexts/LLBE/JobOpenings/application/Remove/JobOpeningRemover
    arguments: [ '@App.jobOpenings.JobOpeningRepository' ]
