services:

  App.jobOpenings.JobOpeningRepository:
    class: ../../../../../Contexts/LLBE/JobOpenings/infrastructure/persistence/MongoJobOpeningRepository
    arguments: ['@App.shared.ConnectionManager']

  App.jobOpenings.JobOpeningCreator:
    class: ../../../../../Contexts/LLBE/JobOpenings/application/JobOpeningCreator
    arguments: ['@App.jobOpenings.JobOpeningRepository']

  App.jobOpenings.JobOpeningUpgrader:
    class: ../../../../../Contexts/LLBE/JobOpenings/application/JobOpeningUpgrader
    arguments: ['@App.jobOpenings.JobOpeningRepository']

  App.jobOpenings.JobOpeningRemover:
    class: ../../../../../Contexts/LLBE/JobOpenings/application/JobOpeningRemover
    arguments: ['@App.jobOpenings.JobOpeningRepository']
