version: '3'

services:
  app:
    build: .
    command: bash -c "npm run build && npm run start"
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongo:27017/dev
    depends_on:
      - mongo
    volumes:
      - .:/code:delegated
      - node_modules:/code/node_modules:delegated

  mongo:
    image: mongo:3.4.6
    volumes:
      - ./data/mongo:/data/db:delegated
    ports:
      - 27017:27017

  openssl:
    volumes:
      - ./ssl:/ssl
    build:
      context: .
      dockerfile: Dockerfile-openssl

volumes:
  node_modules:
