imports:
  - { resource: ./application.yaml }

services:
  LLBE.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@LLBE.shared.ConnectionManager']

  LLBE.shared.EventBus:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/InMemorySyncEventBus
    arguments: []
