imports:
  - { resource: ./application.yaml }

services:
  Mooc.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Mooc.shared.ConnectionManager']

  Mooc.shared.EventBus:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/InMemorySyncEventBus
    arguments: []
