imports:
  - { resource: ./application.yaml }

services:
  App.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: [ '@App.shared.ConnectionManager' ]

  App.Mailer:
    class: ../../../../../src/Contexts/Shared/infrastructure/mail/MockMailer
    arguments: [ '@App.users.UserRepository', '@App.users.UserEmailConfirmator']
