imports:
  - { resource: ./application.yaml }

services:
  App.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@App.shared.ConnectionManager']
