GET http://localhost:3300/status
Accept: application/json

###

POST http://localhost:3300/auth/signup
Content-Type: application/json

{
  "email": "pepo@api.com",
  "password": "123123",
  "userRole": "ROLE_STUDENT"
}

###

POST http://localhost:3300/auth/signin
Content-Type: application/json

{
  "email": "pepe@api.com",
  "password": "123123"
}

###

POST http://localhost:3300/auth/signup
Content-Type: application/json

{
  "email": "manolito@api.com",
  "password": "123123",
  "role": "ROLE_STUDENT"
}

###
