services:

  App.users.UserRepository:
    class: ../../../../../Contexts/LLBE/Users/infrastructure/persistence/MongoUserRepository
    arguments: [ '@App.shared.ConnectionManager' ]

  App.users.UserCreator:
    class: ../../../../../Contexts/LLBE/Users/application/UserCreator
    arguments: [ '@App.users.UserRepository', '@App.users.ConfirmationEmail' ]

  App.users.UserUpdateRegistered:
    class: ../../../../../Contexts/LLBE/Users/application/UserUpdateRegistered
    arguments: [ '@App.users.UserRepository' ]

  App.users.UserLastUpdateResumer:
    class: ../../../../../Contexts/LLBE/Users/application/UserLastUpdateResumer
    arguments: [ '@App.users.UserRepository' ]

  App.users.ConfirmationEmail:
    class: ../../../../../Contexts/LLBE/Users/application/UserConfirmationEmailDealer
    arguments: [ '@App.Mailer', '@App.users.TokenGenerator' ]

  App.users.UserProfiler:
    class: ../../../../../Contexts/LLBE/Shared/application/Users/UserProfiler
    arguments: [ '@App.students.StudentRepository', '@App.companies.CompanyRepository' ]

  App.users.UserEmailConfirmator:
    class: ../../../../../Contexts/LLBE/Users/application/UserEmailConfirmator
    arguments: [ '@App.users.UserRepository' ]

  App.users.UserEmailFinder:
    class: ../../../../../Contexts/LLBE/Users/application/UserEmailFinder
    arguments: [ '@App.users.UserRepository' ]

  App.users.UserAuth:
    class: ../../../../../Contexts/LLBE/Users/application/UserAuth
    arguments: [ '@App.users.TokenGenerator','@App.users.UserRepository', '@App.users.UserProfiler' ]

  App.users.TokenGenerator:
    class: ../../../../../Contexts/LLBE/Users/infrastructure/token/JWTTokenGenerator
    arguments: []

  App.users.AvatarFinder:
    class: ../../../../../Contexts/LLBE/Users/application/AvatarFinder
    arguments: [ '@App.users.UserRepository']

  App.users.AvatarUpdater:
    class: ../../../../../Contexts/LLBE/Users/application/AvatarUpdater
    arguments: [ '@App.users.UserRepository']

  App.users.AvatarRemover:
    class: ../../../../../Contexts/LLBE/Users/application/AvatarRemover
    arguments: [ '@App.users.UserRepository']
