services:

  App.users.UserRepository:
    class: ../../../../../Contexts/LLBE/Users/infrastructure/persistence/MongoUserRepository
    arguments: [ '@App.shared.ConnectionManager' ]

  App.users.UserCreator:
    class: ../../../../../Contexts/LLBE/Users/application/UserCreator
    arguments: [ '@App.users.UserRepository', '@App.users.ConfirmationEmail' ]

  App.users.ConfirmationEmail:
    class: ../../../../../Contexts/LLBE/Users/application/UserConfirmationEmailDealer
    arguments: [ '@App.shared.Mailer', '@App.shared.TokenGenerator' ]

  App.users.UserEmailConfirmator:
    class: ../../../../../Contexts/LLBE/Users/application/UserEmailConfirmator
    arguments: [ '@App.users.UserRepository' ]

  App.users.UserAuth:
    class: ../../../../../Contexts/LLBE/Users/application/UserAuth
    arguments: [ '@App.shared.TokenGenerator','@App.users.UserRepository' ]
