services:

  App.controllers.status.StatusGetController:
    class: ../../../controllers/status/StatusGetController
    arguments: []

  App.controllers.students.StudentPostController:
    class: ../../../controllers/StudentPostController
    arguments: ["@LLBE.students.StudentCreator"]
