services:

  App.controllers.status.StatusGetController:
    class: ../../../controllers/status/StatusGetController
    arguments: []

  App.controllers.auth.SignUpPostController:
    class: ../../../controllers/auth/SignUpPostController
    arguments: ["@App.users.UserCreator"]

  App.controllers.auth.SignInPostController:
    class: ../../../controllers/auth/SignInPostController
    arguments: ["@App.users.UserAuth"]

  App.controllers.auth.EmailVerificationGetController:
    class: ../../../controllers/auth/EmailVerificationGetController
    arguments: [ "@App.users.AuthChecker", "@App.users.UserEmailConfirmator" ]

  App.controllers.students.StudentGetController:
    class: ../../../controllers/students/StudentGetController
    arguments: [ "@App.students.StudentFinder", "@App.users.AuthChecker", "@App.users.StudentRoleChecker" ]

  App.controllers.students.StudentPostController:
    class: ../../../controllers/students/StudentPostController
    arguments: [ "@App.students.StudentCreator", "@App.users.AuthChecker", "@App.users.StudentRoleChecker" ]

  App.controllers.students.StudentPutController:
    class: ../../../controllers/students/StudentPutController
    arguments: [ "@App.students.StudentUpgrader", "@App.users.AuthChecker", "@App.users.StudentRoleChecker" ]

  App.controllers.companies.CompanyGetController:
    class: ../../../controllers/companies/CompanyGetController
    arguments: [ "@App.companies.CompanyFinder", "@App.users.AuthChecker" ]

  App.controllers.companies.CompanyPostController:
    class: ../../../controllers/companies/CompanyPostController
    arguments: [ "@App.companies.CompanyCreator", "@App.users.AuthChecker", "@App.users.CompanyRoleChecker" ]

  App.controllers.companies.CompanyPutController:
    class: ../../../controllers/companies/CompanyPutController
    arguments: [ "@App.companies.CompanyUpgrader", "@App.users.AuthChecker", "@App.users.CompanyRoleChecker" ]

  App.controllers.jobOpenings.JobOpeningGetController:
    class: ../../../controllers/jobOpenings/JobOpeningGetController
    arguments: [ "@App.jobOpenings.JobOpeningFinder", "@App.users.AuthChecker" ]

  App.controllers.jobOpenings.JobOpeningPostController:
    class: ../../../controllers/jobOpenings/JobOpeningPostController
    arguments: [ "@App.jobOpenings.JobOpeningCreator", "@App.users.AuthChecker", "@App.users.CompanyRoleChecker" ]

  App.controllers.jobOpenings.JobOpeningPutController:
    class: ../../../controllers/jobOpenings/JobOpeningPutController
    arguments: [ "@App.jobOpenings.JobOpeningUpgrader", "@App.users.AuthChecker", "@App.users.CompanyRoleChecker" ]

  App.controllers.jobOpenings.JobOpeningDeleteController:
    class: ../../../controllers/jobOpenings/JobOpeningDeleteController
    arguments: [ "@App.jobOpenings.JobOpeningRemover", "@App.users.AuthChecker", "@App.users.CompanyRoleChecker" ]

  App.controllers.enrollments.EnrollmentPostController:
    class: ../../../controllers/enrollments/EnrollmentPostController
    arguments: [ "@App.enrollments.EnrollmentCreator", "@App.users.StudentRoleChecker" ]

  App.controllers.enrollments.EnrollmentDeleteController:
    class: ../../../controllers/enrollments/EnrollmentDeleteController
    arguments: [ "@App.enrollments.EnrollmentRemover", "@App.users.StudentRoleChecker" ]

  App.controllers.enrollments.EnrollmentsGetController:
    class: ../../../controllers/enrollments/EnrollmentsGetController
    arguments: [ "@App.enrollments.EnrollmentsSearcher", "@App.users.CompanyRoleChecker", "@App.students.StudentFinder", "@App.users.UserEmailFinder" ]
