services:

  App.controllers.status.StatusGetController:
    class: ../../../controllers/status/StatusGetController
    arguments: []

  App.controllers.CoursePutController:
    class: ../../../controllers/CoursePutController
    arguments: ["@Mooc.courses.CourseCreator"]

  App.controllers.CoursesCounterGetController:
    class: ../../../controllers/CoursesCounterGetController
    arguments: ["@Mooc.coursesCounter.CoursesCounterFinder"]
