services:

  App.controllers.status.StatusGetController:
    class: ../../../controllers/status/StatusGetController
    arguments: []

  App.controllers.auth.SignUpPostController:
    class: ../../../controllers/auth/SignUpPostController
    arguments: ["@App.users.UserCreator"]

  App.controllers.auth.SignInPostController:
    class: ../../../controllers/auth/SignInPostController
    arguments: ["@App.users.UserAuth"]

  App.controllers.auth.EmailVerificationGetController:
    class: ../../../controllers/auth/EmailVerificationGetController
    arguments: ["@App.users.UserEmailConfirmator"]

  App.controllers.students.StudentPostController:
    class: ../../../controllers/students/StudentPostController
    arguments: ["@App.students.StudentCreator"]
