services:

  # STATUS
  App.controllers.status.StatusGetController:
    class: ../../../controllers/status/StatusGetController
    arguments: [ ]


  # AUTH
  App.controllers.auth.SignUpPostController:
    class: ../../../controllers/auth/SignUpPostController
    arguments: [ "@App.users.UserCreator" ]

  App.controllers.auth.SignInPostController:
    class: ../../../controllers/auth/SignInPostController
    arguments: [ "@App.users.UserAuth" ]

  App.controllers.auth.EmailVerificationGetController:
    class: ../../../controllers/auth/EmailVerificationGetController
    arguments: [ "@App.users.UserEmailConfirmator" ]

  # USER

  App.controllers.user.ProfileGetController:
    class: ../../../controllers/user/ProfileGetController
    arguments: [ "@App.users.UserProfiler" ]

  # STUDENTS
  App.controllers.students.StudentGetController:
    class: ../../../controllers/students/StudentGetController
    arguments: [ "@App.students.StudentFinder" ]

  App.controllers.students.StudentPutController:
    class: ../../../controllers/students/StudentPutController
    arguments: [ "@App.students.StudentUpgrader" ]


  # COMPANIES
  App.controllers.companies.CompanyGetController:
    class: ../../../controllers/companies/CompanyGetController
    arguments: [ "@App.companies.CompanyFinder" ]

  App.controllers.companies.CompanyFetchController:
    class: ../../../controllers/companies/CompanyFetchController
    arguments: [ "@App.companies.CompanyFetcher" ]

  App.controllers.companies.CompanyJobsGetController:
    class: ../../../controllers/companies/CompanyJobsGetController
    arguments: [ "@App.jobOpenings.CompanyJobsFetcher" ]

  App.controllers.companies.CompanyPutController:
    class: ../../../controllers/companies/CompanyPutController
    arguments: [ "@App.companies.CompanyUpgrader" ]


  # JOB OPENINGS
  App.controllers.jobOpenings.JobOpeningGetController:
    class: ../../../controllers/jobOpenings/JobOpeningGetController
    arguments: [ "@App.jobOpenings.JobOpeningFinder" ]

  App.controllers.jobOpenings.JobOpeningFetchController:
    class: ../../../controllers/jobOpenings/JobOpeningFetchController
    arguments: [ "@App.jobOpenings.JobOpeningFetcher" ]

  App.controllers.jobOpenings.JobOpeningPostController:
    class: ../../../controllers/jobOpenings/JobOpeningPostController
    arguments: [ "@App.jobOpenings.JobOpeningCreator" ]

  App.controllers.jobOpenings.JobOpeningPutController:
    class: ../../../controllers/jobOpenings/JobOpeningPutController
    arguments: [ "@App.jobOpenings.JobOpeningUpgrader", "@App.jobOpenings.CompanyJobsFetcher" ]

  App.controllers.jobOpenings.JobOpeningDeleteController:
    class: ../../../controllers/jobOpenings/JobOpeningDeleteController
    arguments: [ "@App.jobOpenings.JobOpeningDeactivator" ]


  # ENROLLMENTS
  App.controllers.enrollments.EnrollmentPostController:
    class: ../../../controllers/enrollments/EnrollmentPostController
    arguments: [ "@App.enrollments.EnrollmentCreator", "@App.enrollments.EnrollmentsFetcher" ]

  App.controllers.enrollments.EnrollmentDeleteController:
    class: ../../../controllers/enrollments/EnrollmentDeleteController
    arguments: [ "@App.enrollments.EnrollmentRemover", "@App.enrollments.EnrollmentsFetcher" ]

  App.controllers.enrollments.EnrollmentsGetController:
    class: ../../../controllers/enrollments/EnrollmentsGetController
    arguments: [ "@App.enrollments.EnrollmentsSearcher" ]

  App.controllers.enrollments.EnrollmentsFetchController:
    class: ../../../controllers/enrollments/EnrollmentsFetchController
    arguments: [ "@App.enrollments.EnrollmentsFetcher" ]

  # Avatar
  App.controllers.avatar.AvatarGetController:
    class: ../../../controllers/avatar/AvatarGetController
    arguments: [ "@App.users.AvatarFinder" ]

  App.controllers.avatar.AvatarPutController:
    class: ../../../controllers/avatar/AvatarPutController
    arguments: [ "@App.users.AvatarUpdater" ]

  App.controllers.avatar.AvatarDeleteController:
    class: ../../../controllers/avatar/AvatarDeleteController
    arguments: [ "@App.users.AvatarRemover" ]
