services:

  App.enrollments.EnrollmentRepository:
    class: ../../../../../Contexts/LLBE/Enrollments/infrastructure/persistence/MongoEnrollmentRepository
    arguments: ['@App.shared.ConnectionManager']

  App.enrollments.EnrollmentCreator:
    class: ../../../../../Contexts/LLBE/Enrollments/application/EnrollmentCreator
    arguments: ['@App.enrollments.EnrollmentRepository']

  App.enrollments.EnrollmentRemover:
    class: ../../../../../Contexts/LLBE/Enrollments/application/EnrollmentRemover
    arguments: ['@App.enrollments.EnrollmentRepository']

  App.enrollments.EnrollmentsSearcher:
    class: ../../../../../Contexts/LLBE/Enrollments/application/EnrollmentsSearcher
    arguments: ['@App.enrollments.EnrollmentRepository']

  App.enrollments.EnrollmentsCounter:
    class: ../../../../../Contexts/LLBE/Enrollments/application/EnrollmentsCounter
    arguments: ['@App.enrollments.EnrollmentRepository']

  App.enrollments.EnrollmentsFetcher:
    class: ../../../../../Contexts/LLBE/Enrollments/application/EnrollmentsFetcher
    arguments: ['@App.enrollments.EnrollmentRepository']
