services:
  App.shared.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['llbe']

  App.shared.Logger:
    class: ../../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  App.shared.EventBus:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/InMemoryAsyncEventBus
    arguments: []

  App.shared.EventBus.DomainEventMapping:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/DomainEventMapping
    arguments: ['!tagged domainEventSubscriber']

  App.shared.EventBus.DomainEventJsonDeserializer:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/DomainEventJsonDeserializer
    arguments: ['@LLBE.shared.EventBus.DomainEventMapping']
