services:
  Mooc.shared.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['mooc']

  Mooc.shared.Logger:
    class: ../../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Mooc.shared.EventBus:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/InMemoryAsyncEventBus
    arguments: []

  Mooc.shared.EventBus.DomainEventMapping:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/DomainEventMapping
    arguments: ['!tagged domainEventSubscriber']

  Mooc.shared.EventBus.DomainEventJsonDeserializer:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/DomainEventJsonDeserializer
    arguments: ['@Mooc.shared.EventBus.DomainEventMapping']
