services:

  App.companies.CompanyRepository:
    class: ../../../../../Contexts/LLBE/Companies/infrastructure/persistence/MongoCompanyRepository
    arguments: [ '@App.shared.ConnectionManager' ]

  App.companies.CompanyCreator:
    class: ../../../../../Contexts/LLBE/Companies/application/Create/CompanyCreator
    arguments: [ '@App.companies.CompanyRepository', '@App.users.UserUpdateRegistered' ]

  App.companies.CompanyUpgrader:
    class: ../../../../../Contexts/LLBE/Companies/application/Update/CompanyUpgrader
    arguments: [ '@App.companies.CompanyRepository' ]

  App.companies.CompanyFinder:
    class: ../../../../../Contexts/LLBE/Companies/application/Find/CompanyFinder
    arguments: [ '@App.companies.CompanyRepository' ]
