services:

  App.students.StudentRepository:
    class: ../../../../../Contexts/LLBE/Students/infrastructure/persistence/MongoStudentRepository
    arguments: ['@App.shared.ConnectionManager']

  App.students.StudentCreator:
    class: ../../../../../Contexts/LLBE/Students/application/StudentCreator
    arguments: ['@App.students.StudentRepository']
