services:

  App.students.StudentRepository:
    class: ../../../../../Contexts/LLBE/Students/infrastructure/persistence/MongoStudentRepository
    arguments: ['@App.shared.ConnectionManager']

  App.students.StudentCreator:
    class: ../../../../../Contexts/LLBE/Students/application/Create/StudentCreator
    arguments: ['@App.students.StudentRepository']

  App.students.StudentUpgrader:
    class: ../../../../../Contexts/LLBE/Students/application/Update/StudentUpgrader
    arguments: ['@App.students.StudentRepository', '@App.users.UserLastUpdateResumer']

  App.students.StudentFinder:
    class: ../../../../../Contexts/LLBE/Students/application/Find/StudentFinder
    arguments: ['@App.students.StudentRepository']
