services:

  LLBE.students.StudentRepository:
    class: ../../../../../Contexts/LLBE/Students/infrastructure/persistence/MongoStudentRepository
    arguments: ['@LLBE.shared.ConnectionManager']

  LLBE.students.StudentCreator:
    class: ../../../../../Contexts/LLBE/Students/application/StudentCreator
    arguments: ['@LLBE.students.StudentRepository']
