services:

  App.students.StudentRepository:
    class: ../../../../../Contexts/LLBE/Students/infrastructure/persistence/MongoStudentRepository
    arguments: ['@App.shared.ConnectionManager']

  App.students.StudentCreator:
    class: ../../../../../Contexts/LLBE/Students/application/StudentCreator
    arguments: ['@App.students.StudentRepository', '@App.users.UserUpdateRegistered']

  App.students.StudentUpgrader:
    class: ../../../../../Contexts/LLBE/Students/application/StudentUpgrader
    arguments: ['@App.students.StudentRepository']

  App.students.StudentFinder:
    class: ../../../../../Contexts/LLBE/Students/application/StudentFinder
    arguments: ['@App.students.StudentRepository']

